### ISSUE TITLE
outreach

### ISSUE THREAD

**Issue by adrelanos** [nyxnor/onion-wash#7]
I'll be sharing your Tor / security related projects on special media.

* https://twitter.com/Whonix/status/1495084528343597058
* https://twitter.com/Whonix/status/1495050799399030790
* https://twitter.com/Whonix/status/1489588468653170690

(Also auto posted to facebook and perhaps a few others if automation is functional. Otherwise might be posted elsewhere depending on contributor availability.)

But hootsuite accepts only image, gif, video (probably social media limitation).

If https://asciinema.org/a/463445?autoplay=1 was available as gif or video, I'd like to share that too.

Might also be useful to announce on mailing lists here's a small list but probably a lot more places (Tor forum?) nowadays.
https://www.whonix.org/wiki/Dev/Redistribution#Announcement

**Comment by nyxnor** [comment]
Thank you for the outreach, would be glad to have more contributors to improve.

> But hootsuite accepts only image, gif, video (probably social media limitation).

I will see if asciinema can make gifs. Will also update that video.

> Might also be useful to announce on mailing lists here's a small list but probably a lot more places (Tor forum?) nowadays.

I tried vitor on a tpo issue https://gitlab.torproject.org/tpo/core/tor/-/issues/40536
 because it would be much better if they scrutinized the code or even wrote a better one in C so it could be shipped together with tor as visudo is shipped with sudo, but they never replied...

**Comment by nyxnor** [comment]
https://github.com/asciinema/asciinema-server/issues/189#issuecomment-840382785
Installed this docker project on a disposable whonix workstation, loving this disposable capability.

https://user-images.githubusercontent.com/69700936/154859273-3663ad6e-714e-4c48-af39-8e4a9017d73b.mp4

Github will say the file I corrupt, but doing `scurl-download https://user-images.githubusercontent.com/69700936/154859273-3663ad6e-714e-4c48-af39-8e4a9017d73b.mp4` worked on playing the video with VLC.

**Comment by adrelanos** [comment]
I had no idea...

> Video is too tall
> 
> Twitter supports videos up to 1280 pixels tall. Your video is 1400 pixels tall.
> Video is too wide
> 
> Twitter supports videos up to 1280 pixels wide. Your video is 2305 pixels wide.
> Video is too long
> 
> Twitter supports videos up to 2 minutes and 20 seconds long. Your video is 2 minutes and 23.8 seconds long.

**Comment by adrelanos** [comment]
Could post to facebook at least but twitter... No luck...

https://help.twitter.com/en/using-twitter/twitter-videos

**Comment by nyxnor** [comment]
Shorter video and smaller window. if it doesn't work, don't worry.
https://user-images.githubusercontent.com/69700936/154866990-102111cd-6ce4-4177-9b69-42ea436d865c.mp4

**Comment by adrelanos** [comment]
Yeah. Twitter videos are a science.

>Video is too wide
>
>Twitter supports videos up to 1280 pixels wide. Your video is 1338 pixels wide.

**Comment by nyxnor** [comment]
no problem, leave it.

**Comment by adrelanos** [comment]
Figured out how to resize size and done.

https://twitter.com/Whonix/status/1495532883087347713

**Comment by nyxnor** [comment]
thanks :)

**Comment by nyxnor** [comment]
sent msg on IRC about vitor. No reply yet, if they don't reply, I will have nothing to post here

Edit: no answer.

**Comment by nyxnor** [comment]
Thank you for the outreach. To show the impact you have made, I am showing what is available at the `traffic` page for the maintainer https://github.com/nyxnor/onionwash/graphs/traffic

An old saying: _Those who are not seen, are not remembered_

### Transparency report

![image](https://user-images.githubusercontent.com/69700936/155731863-862a89ae-a01c-489b-80d5-4b86958022a6.png)
![image](https://user-images.githubusercontent.com/69700936/155732030-def83e24-568d-4668-991b-9fbe20a055e9.png)
![image](https://user-images.githubusercontent.com/69700936/155731242-c58982a0-1a39-4d6e-8bcf-98d37fcbe819.png)
